spring:
  r2dbc:
    url: r2dbc:postgresql://articledb:5432/article
    username: postgres
    password: postgres

logging:
  level:
    com:
      creationline:
        k8sthinkit:
          sample1: DEBUG

accesscount:
  url: http://accesscount:8080

opentracing:
  jaeger:
    enabled: false
    udp-sender:
      host: localhost
      port: 6831
    log-spans: true
