spring:
  profiles:
    include:
      - base
  r2dbc:
    url: r2dbc:postgresql://articledb:5432/article
    username: ${database.username}
    password: ${database.password}
# following credentials need override by environment variables
database:
  username: ''  # DATABASE_USERNAME
  password: ''  # DATABASE_PASSWORD
accesscount:
  url: http://accesscount:8080
