spring:
  profiles:
    include:
      - base
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://articledb:5432/article
    username: postgres
    password: postgres
accesscount:
  hostname: accesscount
  port: 8080
