spring:
  r2dbc:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
# following credentials need override by environment variables
database:
  url: ''       # DATABASE_URL
  username: ''  # DATABASE_USERNAME
  password: ''  # DATABASE_PASSWORD
accesscount:
  url: http://accesscount:8080
