stages:
  - build

.build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    REPOSITORY: $CI_REGISTRY_IMAGE
  script:
    # DEBUG CODE (fllowing this line)
    - set -euvx
    - echo "PWD = ${PWD}"
    - echo "CI_PROJECT_DIR = ${CI_PROJECT_DIR}"
    - ls -la ./
    - ls -la ./scripts
    - ls -la ./scripts/${SCRIPT_FILE}
    # DEBUG CODE (above this line)
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - cd $CI_PROJECT_DIR
    - ./scripts/$SCRIPT_FILE $COMPONENT

.build-prod:
  extends: .build
  variables:
    SCRIPT_FILE: 'kaniko-build-production.sh'

build-prod-article:
  extends: .build-prod
  variables:
    COMPONENT: article

build-prod-accesscount:
  extends: .build-prod
  variables:
    COMPONENT: accesscount

build-prod-rank:
  extends: .build-prod
  variables:
    COMPONENT: rank

build-prod-website:
  extends: .build-prod
  variables:
    COMPONENT: website
