version: '3'

services:

  articledb:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: article
    volumes:
      - type: bind
        source: ../../../src/article/database/schema.sql
        target: /docker-entrypoint-initdb.d/schema.sql
        read_only: true
    ports:
      - '127.0.0.1:5431:5432'  # postgres access from host

  accesscountdb:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: accesscount
    volumes:
      - type: bind
        source: ../../../src/accesscount/database/schema.sql
        target: /docker-entrypoint-initdb.d/schema.sql
        read_only: true
    ports:
      - '127.0.0.1:5432:5432'  # postgres access from host

  rankdb:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rank
    volumes:
      - type: bind
        source: ../../../src/rank/database/schema.sql
        target: /docker-entrypoint-initdb.d/schema.sql
        read_only: true
    ports:
      - '127.0.0.1:5433:5432'  # postgres access from host

  article:
    depends_on:
      - articledb
    image: article:dev-docker
    environment:
      DEBUG: 'false'
      ENABLE_DEBUGGER: 'false'
      DEBUGGER_PORT: '8000'
    volumes:
      - type: bind
        source: ../../../src/article/
        target: /article/
    ports:
      - '127.0.0.1:8081:8080'  # web
      - '127.0.0.1:8001:8000'  # debugger

  accesscount:
    depends_on:
      - accesscountdb
    image: accesscount:dev-docker
    environment:
      DEBUG: 'false'
      ENABLE_DEBUGGER: 'false'
      DEBUGGER_PORT: '8000'
    volumes:
      - type: bind
        source: ../../../src/accesscount/
        target: /accesscount/
    ports:
      - '127.0.0.1:8082:8080'  # web
      - '127.0.0.1:8002:8000'  # debugger

  rank:
    depends_on:
      - rankdb
    image: rank:dev-docker
    environment:
      DEBUG: 'false'
      ENABLE_DEBUGGER: 'false'
      DEBUGGER_PORT: '8000'
    volumes:
      - type: bind
        source: ../../../src/rank/
        target: /rank/
    ports:
      - '127.0.0.1:8083:8080'  # web
      - '127.0.0.1:8003:8000'  # debugger

  website:
    image: website:dev-docker
    environment:
      ARTICLE_BASE_URL_FROM_SERVER: http://article:8080
      ARTICLE_BASE_URL_FROM_CLIENT: http://localhost:8081
      RANK_BASE_URL_FROM_SERVER: http://rank:8080
      RANK_BASE_URL_FROM_CLIENT: http://localhost:8083
    volumes:
      - type: bind
        source: ../../../src/website/
        target: /website/
    ports:
      - '127.0.0.1:3000:3000'  # web
      - '127.0.0.1:9229:9229'  # debugger
