spring:
  application:
    name: rank

server:
  port: 8080

timezone: Asia/Tokyo

rank:
  schedule:
    daily: '0 0 0 * * *'

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      defaults:
        enabled: false
      prometheus:
        enabled: true

# disable tracing by default
opentracing:
  jaeger:
    enabled: false
