apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment-article.yaml
- service-article.yaml
- ingress-article.yaml
- statefulset-articledb.yaml
- service-articledb.yaml
- deployment-accesscount.yaml
- service-accesscount.yaml
- ingress-accesscount.yaml
- statefulset-accesscountdb.yaml
- service-accesscountdb.yaml
- deployment-rank.yaml
- service-rank.yaml
- ingress-rank.yaml
- statefulset-rankdb.yaml
- service-rankdb.yaml
- deployment-website.yaml
- service-website.yaml
- ingress-website.yaml

configMapGenerator:
- name: article-init-db
  files:
  - config/articledb/schema.sql
- name: accesscount-init-db
  files:
  - config/accesscountdb/schema.sql
- name: rank-init-db
  files:
  - config/rankdb/schema.sql

images:
- name: article
  newName: registry.example.com/path/to/repository/article
- name: accesscount
  newName: registry.example.com/path/to/repository/accesscount
- name: rank
  newName: registry.example.com/path/to/repository/rank
- name: website
  newName: registry.example.com/path/to/repository/website
