server:
  port: 8080

timezone: Asia/Tokyo

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      defaults:
        enabled: false
      prometheus:
        enabled: true
