apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment-article.yaml
- service-article.yaml
- ingress-article.yaml
- deployment-accesscount.yaml
- service-accesscount.yaml
- ingress-accesscount.yaml
- deployment-rank.yaml
- service-rank.yaml
- ingress-rank.yaml
- deployment-website.yaml
- service-website.yaml
- ingress-website.yaml

configMapGenerator:
- name: article-init-db
  files:
  - config/articledb/schema.sql
- name: accesscount-init-db
  files:
  - config/accesscountdb/schema.sql
- name: rank-init-db
  files:
  - config/rankdb/schema.sql

secretGenerator:
- name: articledb-config
  envs:
  - config/articledb/config.env
- name: accesscountdb-config
  envs:
  - config/accesscountdb/config.env
- name: rankdb-config
  envs:
  - config/rankdb/config.env


images:
- name: article
  newName: registry.gitlab.com/thinkit-kubernetes-sample1/article
- name: accesscount
  newName: registry.gitlab.com/thinkit-kubernetes-sample1/accesscount
- name: rank
  newName: registry.gitlab.com/thinkit-kubernetes-sample1/rank
- name: website
  newName: registry.gitlab.com/thinkit-kubernetes-sample1/website
