apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment-article.yaml
- service-article.yaml
- ingress-article.yaml
- deployment-accesscount.yaml
- service-accesscount.yaml
- ingress-accesscount.yaml
- deployment-rank.yaml
- service-rank.yaml
- ingress-rank.yaml
- deployment-website.yaml
- service-website.yaml
- ingress-website.yaml

secretGenerator:
- name: article-config
  envs:
  - config/article/config.env
- name: accesscount-config
  envs:
  - config/accesscount/config.env
- name: rank-config
  envs:
  - config/rank/config.env

configMapGenerator:
- name: website-config
  envs:
  - config/website/config.env

images:
- name: article
  newName: registry.gitlab.com/thinkit-kubernetes-sample1/article
- name: accesscount
  newName: registry.gitlab.com/thinkit-kubernetes-sample1/accesscount
- name: rank
  newName: registry.gitlab.com/thinkit-kubernetes-sample1/rank
- name: website
  newName: registry.gitlab.com/thinkit-kubernetes-sample1/website
