apiVersion: v1
kind: Service
metadata:
  labels:
    app: accesscount
  name: accesscount
spec:
  type: ClusterIP
  selector:
    app: accesscount
  ports:
  - name: web
    port: 8080
    targetPort: web
