apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- statefulset-articledb.yaml
- service-articledb.yaml
- statefulset-accesscountdb.yaml
- service-accesscountdb.yaml
- statefulset-rankdb.yaml
- service-rankdb.yaml

secretGenerator:
- name: article-config
  envs:
  - config/article/config.env
- name: accesscount-config
  envs:
  - config/accesscount/config.env
- name: rank-config
  envs:
  - config/rank/config.env

configMapGenerator:
- name: website-config
  envs:
  - config/website/config.env
- name: article-init-db
  files:
  - config/articledb/schema.sql
- name: accesscount-init-db
  files:
  - config/accesscountdb/schema.sql
- name: rank-init-db
  files:
  - config/rankdb/schema.sql

images:
- name: article
  newName: article # registry.gitlab.com/creationline/thinkit-kubernetes-sample1/article
  newTag: dev
- name: accesscount
  newName: accesscount # registry.gitlab.com/creationline/thinkit-kubernetes-sample1/accesscount
  newTag: dev
- name: rank
  newName: rank # registry.gitlab.com/creationline/thinkit-kubernetes-sample1/rank
  newTag: dev
- name: website
  newName: website # registry.gitlab.com/creationline/thinkit-kubernetes-sample1/website
  newTag: dev

patches:
- deployment-accesscount.yaml
- deployment-article.yaml
- deployment-rank.yaml
- deployment-website.yaml