apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  template:
    spec:
      containers:
      - name: website
        ports:
        - name: debugger
          containerPort: 9229
          protocol: TCP
