apiVersion: apps/v1
kind: Deployment
metadata:
  name: article
spec:
  template:
    spec:
      containers:
      - name: article
        env:
        - name: DEBUG
          value: 'false'
        - name: ENABLE_DEBUGGER
          value: 'false'
        - name: DEBUGGER_PORT
          value: '8000'
        ports:
        - name: debugger
          containerPort: 8000
          protocol: TCP
